### ISSUE TITLE
Scrollable Dialog

### ISSUE THREAD

**Issue by rcheung9** [olton/Metro-UI-CSS#1006]
Is it possible to make the dialog scrollable?

**Comment by chongzia** [comment]
We have the same problem = =.
In some functional components can't show more content

**Comment by olton** [comment]
Maybe need to create a scrollable container inside a dialog?

**Comment by olton** [comment]
@rcheung9 @chongzia https://codepen.io/olton/pen/ddxmeb/

**Comment by chongzia** [comment]
charm and dialog or add new one components 
implementation and charm or dialog same effect
But can scroll to display more content.
Or incorporate these is functions to the dialog and charm
Especially the charm

because In the framework of no longer can't find a can as the mobile terminal additional display the use of the page

**Comment by olton** [comment]
I do not have plans to add any scrollable components for the charms or dialogue. It's all elementary and easily added outside the Metro 4.

**Comment by chongzia** [comment]
haha~
I accept the reality However in the your concept CSS seems to be it shouldn't exist.
So I've been following your concept.
