### ISSUE TITLE
Change CSS selector for in Tile.less from a contains * to a starts with ^.

### ISSUE THREAD

**Issue by lobtheslob** [olton/Metro-UI-CSS#1109]
My company has started using metro-ui-css to implement their new client facing portal, but we are having initial style guide conflicts. Would you be able to to change the css selectors in Tile.less from a  contains
eg.
```
[class*=tile-] {
  //code
} 
```
to starts with eg.
```
[class^=tile-] {
  //code
} 
```
?

**Comment by olton** [comment]
Hi @lobtheslob 
Your request cannot be implemented in this time, because the tile class attribute can be implemented in this way `<div class="my-custom-class tile-medium"></div>`.

Your suggestion will restrict the task of classes for tile only in the form `<div class="tile-medium my-other-class"></div>`, must be exceptionally as a first definition.

**Comment by lobtheslob** [comment]
Thank you for taking a look at it. We will look for other solutions on our end.

**Comment by olton** [comment]
@lobtheslob 
I change definition 
`[class*=tile-] {..}` 
to 
`.tile-small, .tile-medium, ,tile-wide, .tile-large, .tile-app {...}`
**wait for 4.2.8**

**Comment by lobtheslob** [comment]
That's awesome. Thank you!
