### ISSUE TITLE
[POLL] What a framework support should I add first?

### ISSUE THREAD

**Issue by olton** [olton/Metro-UI-CSS#1287]
What a framework support should I add first? 
Please select emoji:
React - **Laugh**
Angular - **Hooray**
Vue - **Heart**
None - **Confused**

**Comment by dagnelies** [comment]
It might sound odd, but I'd vote for _"none"_. I'd rather favor that your effort is put into tweaking the current widgets.

I'm probably a minority here, but some of us use plain js (or ts), or other frameworks like https://ractive.js.org/ . Moreover, all these frameworks have (I think) something in common: in order to easily wrap your widgets, you need to:

- be able to initialize them manually (before it's added to the dom)
- be able to get/set data/properties programmatically
- ...in some cases also destroy them to free up event handlers or so

 I think that by providing/documenting these 3 key aspects, it would make it much more easy to write wrappers for those frameworks.

**Comment by olton** [comment]
@dagnelies 
1) You can initialize any Metro 4 components without data-role with role-name function.
2) Almost all attributes that can be changed in runtime are described in the documentation.
3) Some components already have a destroy method, for some, it is still being developed.

**Comment by dagnelies** [comment]
How exactly to you initialize a component per scripting? I must have missed that point in the docs.

**Comment by olton** [comment]
as usual jquery plugin
```
<input type="text" id="my-input">

<script>
   $("#my-input").input();
</script>

```

**Comment by olton** [comment]
Soon Edge will switch to Chromium and all problems will be solved :)

**Comment by hydexon** [comment]
Some feedback about using Metro Framework with Vue.js and probably apply to other frameworks:
- A lot of js components (i.e ListView) is pretty hard to integrate to Vue.js since relies too much of jQuery, states and is a bit undocumented.
- Some components which you acclaim doesn't need the `date-` attributes, are not documented, also modifiying the data attributes with `$(el).data()` doesn't work either.
- Forget any hope of trying to make the Select component work in Vue.js if the Select's data needs an Ajax call.
- Many people calls integrating a popular js framework (Angular, React, Vue) with jQuery as aborrent and bloated.
- Not all the components can be initialized with js (see Tabs)

**Comment by olton** [comment]
@hydexon 
1) Initially, for Metro 4, integration with the frameworks of Vue, Angular, React, etc. was never announced. Metro 4 was developed as a fast clear library for rapid prototyping and use even without knowledge of javascript.
2) All component who has an attribute `data-role` can be initialized by calling the appropriate function
3) `Some components which you acclaim doesn't need the date- attributes` - It is possible in more detail, what do you mean by this?

**Comment by olton** [comment]
Creating bindings and the Metro 4 version for one of the frameworks is the next step, if I have enough health for it. There is no money for it anyway :)

**Comment by morrisjdev** [comment]
@olton
I started implementing some of your components in Angular two months ago but I only have limited time to work on it.

You can take a look at it (https://github.com/morrisjdev/ng-metro4).

I have not written a documentation or any installation instructions and also only some of the beautiful components are implemented. But you can take a first look at it.

I will work on it in the next week's.
