### ISSUE TITLE
Tag-input cannot set value

### ISSUE THREAD

**Issue by ZYSHAQ** [olton/Metro-UI-CSS#1639]
**Describe the bug**
Setting a tag-input value does not work:
1. The firstChild input that is created under the <dev> element has a fixed value property.
2. Trying to dig deeper into the value of the firstChild input under the <dev> element returns "localhost says"

**To Reproduce**
JS will show the value, however, it'll not update it.
https://codepen.io/ZYSHAQ/pen/RwRbKaB

**Expected behavior**
Set the value of taginput during runtime.

**Desktop (please complete the following information):**
 - Metro Version [e.g. 4.3.4]

**Smartphone (please complete the following information):**
 - Device: Computer
 - OS: Latest Windows 64 bit
 - Browser Version 85.0.4183.121 (Official Build) (64-bit)
 - Metro Version: latest version

**Comment by olton** [comment]
the logic of your example is not clear

**Comment by ZYSHAQ** [comment]
I followed the docS to set the value of the tag input during runtime. It’s not working.

**Comment by olton** [comment]
https://codepen.io/olton/pen/rNLBwwj

**Comment by olton** [comment]
create your example on codepen.io

**Comment by n-mam** [comment]
Sure I'll do that and update here once done, first thing tomorrow morning. Thanks.

**Comment by n-mam** [comment]
I have created the pen [here](https://codepen.io/n-mam/pen/ZEeQYBv)

**Comment by olton** [comment]
You want get access to the component before a component will be created. A lot of components in Metro 4 create as complex elements. Metro requires time to create these. You must consider this.

https://codepen.io/olton/pen/oNZbbqr?editors=1011

**Comment by n-mam** [comment]
@olton that was a very helpful pointer, thanks. 

I actually have a metro.dialog which creates the tag input element as shown below (AddNewPointCloudView()). Now the thing is that getTags function which you wrote in the pen fails in all 3 callbacks (i.e. when executed directly inline from the callbacks).. The order is onShow first then comes onOpen and then finally onDialogCreate.. I was hoping that It should have at-least executed successfully from onDialogCreate because it seems to be the last callback.. but no it fails there as well.. It is only when I execute it after a timeout of 3 secs (from inside onDialogCreate) that it succeeds.. is there a more better way do do this ? either that or if you could point me to a callback where the elements are guaranteed to have been created then that should also be fine..

![image](https://user-images.githubusercontent.com/17683324/117950147-84a2dc80-b330-11eb-8952-da4b367c7727.png)

**Comment by olton** [comment]
Please create  for Dialog a separate issue

**Comment by n-mam** [comment]
sure, I can do that. Thanks again for the lead.
