### ISSUE TITLE
Metro-UI TypeScript type definitions

### ISSUE THREAD

**Issue by Asido** [olton/Metro-UI-CSS#492]
I am using MetroUI script files in TypeScript code and I am missing type definitions (.d.ts files).

I think it would be beneficial to create them and submit to TypeScript definition repository: https://github.com/borisyankov/DefinitelyTyped/

For people who are unaware what they are used for, it's to allow TypeScript Language Service (TLS) inside Visual Studio to provide intellisense and and to enforce type safety.

I have declared an interface for my personal use for metro-dialog.js like so:
```TypeScript
interface DialogOptions {
    icon?: any; // false or html tag
    title?: string;
    content?: string;
    flat?: boolean;
    shadow?: boolean;
    overlay?: boolean;
    draggable?: boolean;
    width?: any; // number or string
    height?: any; // number or string
    padding?: number;
    position?: any; // 'default' or object { offsetX, offsetY }
    sysButtons?: any; // false or object { btnClose, btnMax, btnMin }
}

interface JQueryStatic {
    Dialog(params: DialogOptions): JQuery;
}
```

I'll probably end up creating the definitions for the whole MetroUI, but contribution is welcome.

**Comment by vhanla** [comment]
To use with TypeScript this is how I did:

First: added a custom TypeScript definition file in `node_modules/metro4-dist/js/` directory (I know it is not the proper way since npm manager will blow up all changes on update), since it is not available on [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) library, which could be `npm install -D @types/metro4-dist` but there is none, so this will contain that new custom file:
- metro4-dist/js/metro.d.ts 
```ts
declare module "*";
var Metro:any;
export = Metro;
```
Then we modify `node_modules/metro4-dist/package.json`, adding these two lines:
```json
"main": "./js/metro.js",
"typings": "./js/metro.d.ts",
```

Finally: just import JQuery and its TypeScript definition if not already:
I installed jquery type `npm i -D @types/jquery`

```ts
import * as JQuery from 'jquery';
import Metro from 'metro4-dist';
Metro
```
That'll do. 

You can also use `tsconfig.js` options like `noImplicitAny`, `typeRoots`, etc.

More about jQuery plugins importing at: [Import JQuery plugins in TypeScript](https://stackoverflow.com/questions/12719529/using-jquery-plugin-in-typescript#12722003)
