### ISSUE TITLE
Navigation Bar working but dropdown icon didn't show up

### ISSUE THREAD

**Issue by jomsk1e** [olton/Metro-UI-CSS#661]
Hi Sergey, 

I'm having a hard time showing the dropdown icon using Navigation bar, what I mean with 'dropdown icon' is the arrow going down icong with the dropdowns. It didn't show up. 

Included are: 

metro-bootstrap.css
metro-bootstrap-responsive.css
iconFont.css
jquery-2.1.1.min.js
jquery-ui.min.js
metro.min.js
jquery.mousewheel.js
prettify.js
load-metro.js

Here's the markup I am using (Please disregard all asterisk (e.g <*nav>), I'm having a hard time copying the markup here. Advance Thanks!!):  

```
<*nav class="navigation-bar dark">
            <*nav class="navigation-bar-content">
                <*div class="element">
                        <*a class="dropdown-toggle" href="#">HOME</a>
                        <*ul class="dropdown-menu" data-role="dropdown">
                            <*li><*a href="#">Main</a></li>
                            <*li><a href="#">File Open</a></li>
                            <*li class="divider"></li>
                            <*li><a href="#">Print...</a></li>
                            <*li class="divider"></li>
                            <*li><a href="#">Exit</a></li>
                        </*ul>
                </*div>
            </*nav>
        </nav>
```

![metro_dropdown](https://cloud.githubusercontent.com/assets/6386088/4779220/efda9196-5c20-11e4-9507-3df9a02c1e1b.png)

**Comment by Mikael79** [comment]
Hello, 
I have the same problem and the fonts are in order.

The Icon shows in Chrome but not in IE.
The Icons in "iconFont" works, but not "metroSysIcons".

There is a small differense in the CSS between "iconFont" and "metroSysIcons", the "iconFont" has a .EOT-file and the following input: "src: url('../fonts/iconFont.eot?#iefix') format('embedded-opentype')". The metroSysIcons does not have a .EOT-file or that input in the CSS.

It is strange because the Icon appears in IE on your real site (metroui.org.ua). But not in the downloades files.

 Best regards
/Mikael
