### ISSUE TITLE
Metro UI and AJAX

### ISSUE THREAD

**Issue by olton** [olton/Metro-UI-CSS#683]
very often ask the question: if I downloaded the template via Ajax, how do I initialize components?

answer: set the js global parameter METRO_AUTO_REINIT to true

**Comment by Livshitz** [comment]
This is not fully correct, and there're many similar issues closed by you without properly addressing this.

'$.Metro.init' observers mutation of only newly added item, and checks if they CONTAIN data-role:
`plugins = obj.find("[data-role]");` 
Which means that if you have a carousel for example, and you 'lazy-load' new items, this observation will not trigger re-init of the widget.
And it's also not really 'Re-Init' because it only constructs a new widget, not rebuilding it.

You should consider adding special treatment for that.

Anyway, I created this method to request 'ReInit' for specific widget with new items:
`$.Metro.forceInit = function(widget){
    var widgets = $("[data-role='" + widget + "']"); 
    if (widgets.length) {
        $.each(widgets, function(){
            var _this = $(this);
            var roles = _this.data('role').split(/\s*,\s*/);
            roles.map(function(func){
                try {
                    if ($.fn[func] !== undefined) {
                        $.fn[func].call(_this, 'destroy');
                        $.fn[func].call(_this);
                        _this.data(func+'-initiated', true);
                    }
                } catch(e) {
                    if (window.METRO_DEBUG) {
                        console.log(e.message, e.stack);
                    }
                }
            });
        });
    }
}
`
