### ISSUE TITLE
DatePicker input field can't be cleared

### ISSUE THREAD

**Issue by akotulu** [olton/Metro-UI-CSS#844]
Currently I didn't find a way to clear date field after it is filled accidentally. Tried to add cross clear button but it places itself on top of calendar button.

**Comment by rd-rauf** [comment]
I am also facing the same issue. Couldn't find an in built method to do so. I tried clearing the input but doing so doesn't un-select the already selected date. Please at least suggest some workaround.

**Comment by krokofant** [comment]
I have a problem which I think i related. I'm using this with Aurelia and trying to listen to value-changes on the input. Without Metro it works fine but with metro the input value doesn't seem to really change. Weird.

**Comment by calway** [comment]
The problem still exists. I had the same idea as @akotulu but besides that issue you would also have to hack the clear code onto the button. I could get two buttons using a buttongroup but both open the calendar. In fact any click inside the div simply toggles the calendar.

**Comment by olton** [comment]
use form reset button

**Comment by calway** [comment]
A form reset button would reset the entire form. We just want to clear this one field. It would also be an alternative to enable user input in the associated input field so you could manually clear the contents.

**Comment by calway** [comment]
Well I decided to take a closer look. Hacked a solution by adding a button group instead of a single button. The second button is a mif-cancel which I added an onclick call to that simply clears the underlying field. 
Only side effect I have is that clicking the cancel button still opens the calendar but I can live with that for know.

Code looks something like this:
`<div class="input-control text" id="datepicker">`
`    <input type="text">`
`<div class="button-group">`
`<button class="button"><span class="mif-calendar"></span></button>`
`<button class="button" onclick="ResetField();"><span class="mif-cancel"></span></button>`
`</div>`
`</div>`

**Comment by olton** [comment]
i will add feature to clear datepicker in Metro 4
