### ISSUE TITLE
Metro 4, DatePicker and TimePicker prototypes

### ISSUE THREAD

**Issue by olton** [olton/Metro-UI-CSS#987]
https://metroui.org.ua/v4/datepicker.html
https://metroui.org.ua/v4/timepicker.html

**Comment by rcheung9** [comment]
Time picker is cool, works well on mobile touchscreen devices.

I noticed you can't click on the times and instead need to use drag and pull to swipe the roller or use the mouse wheel.  Depending on your scroll wheel settings, you can be scrolling through 5-6 numbers at a time.  Would be good to have arrows up and down to move the roller on desktop because right now you have to hold down mouse button and move mouse in up / down direction to select a number.  Not very intuitive.

I am a fan of this time picker where you can click on the number and pop out a 3x4 grid of values to choose from (01 - 12 for hours, 00 - 55 with 5 min increments for minute) and you can quickly toggle AM/PM.

https://eonasdan.github.io/bootstrap-datetimepicker/#inline
